output: /home/nutzio/Projects/SceneCollisionNet/benchmark
device: cuda:0
num_workers: 4        # Defaults to os.cpu_count() if not specified. Note: set to 0 if vis=1
vis: 1                # output visualizations
iterations: 1000

model:
  name: scene_coll_net
  path: /home/nutzio/Projects/SceneCollisionNet/weights

dataset:
  meshes: /home/nutzio/Projects/SceneCollisionNet/datasets/shapenet/
  batch_size: 1
  query_size: 64
  trajectories: 1