output: /home/nicolasschreiber/Projects/SceneCollisionNet/benchmark
device: cuda:0
# num_workers: 4        # Defaults to os.cpu_count() if not specified.
iterations: 250

model:
  name: self_coll_nn
  path: /home/nicolasschreiber/Projects/SceneCollisionNet/models

dataset:
  batch_size: 512
