output: /home/nicolasschreiber/Projects/SceneCollisionNet/benchmark
device: cuda:0
num_workers: 4        # Defaults to os.cpu_count() if not specified. Note: set to 0 if vis=1
vis: 1                # output visualizations
iterations: 35

model:
  name: scene_coll_net
  path: /home/nicolasschreiber/Projects/SceneCollisionNet/models

dataset:
  meshes: /media/nicolasschreiber/data/SceneCollisionNetData/datasets/shapenet
  batch_size: 30
  query_size: 64
  trajectories: 1
